### ISSUE TITLE
[Ehancement] lyrics via musixmatch

### ISSUE THREAD

**Issue by windowsrefund** [ncmpcpp/ncmpcpp#209]
Any chance the following site can be added as a source for the lyrics fetcher? The site was reported when I attempted to fetch from 'the Internet'. For example, when looking for lyrics to the track 'This is the night' by Cygnosic, they were found on 
https://www.musixmatch.com/lyrics/CygnosiC/This-Is-the-Night

I don't know anything about this site though and don't know if they offer an api. If not, I suspect scraping would kina suck.

**Comment by arybczak** [comment]
Fixed in d08e76c7ed2177c086ff7cf0c41c07c1a739178d.
