### ISSUE TITLE
Wait for a sufficiently large screen and do not terminate

### ISSUE THREAD

**Issue by ManDay** [ncmpcpp/ncmpcpp#259]
With, among other situations, a tiling WM, the console may frequently change size when the window is shuffled or rearraged. In that case it would be desireable if ncmpcpp would not terminate fatally with an error but instead just remain in a non-functional state until the screen changes back to a sufficient size.

I can not anticipate how easy ncurses allows for such a solution, but optimally, in my opinion, such a "non-functional" instance of ncmpcpp would still have generic keybindings (play/pause, volume change, etc.) while other controls may optionally be disabled.

**Comment by Zopiac** [comment]
Agreed. ncdu has this functionality.

`Warning: terminal too small,
 please either resize your terminal,
 press i to ignore, or press q to quit.`

Alternatively, a simplified interface below a certain size.

**Comment by j-n-f** [comment]
I'm adding my support for this request. I've had a similar issue, and find that other TUI apps like `tig` don't suffer this issue.
