### ISSUE TITLE
use log scale for the fftw

### ISSUE THREAD

**Issue by Wang-Yue** [ncmpcpp/ncmpcpp#326]
currently fftw visualization is shown in linear scale. it is better to show that in log scale.

**Comment by arybczak** [comment]
If you come up with log scale that looks good, I'm going to use it. Current approach is the best I was able to come up with through experimentation.

The relevant code is here: https://github.com/arybczak/ncmpcpp/blob/master/src/screens/visualizer.cpp#L418

It's very easy to change it and experiment.

**Comment by arybczak** [comment]
Unfortunately this looks much worse than current implementation. What songs have you tested this on? It pretty much covers the whole screen in bars for me.

**Comment by Wang-Yue** [comment]
@arybczak  It doesn't cover my whole screen at all. The samples I use are some classical music so it may be a lot quieter than pop/rock.  Probably with some scaling we can make it nicer. But the idea is to to use log scale rather than linear scale.
