### ISSUE TITLE
terminate called after throwing an instance of 'MPD::ClientError'

### ISSUE THREAD

**Issue by djvs** [ncmpcpp/ncmpcpp#330]
No clear cause per se, going into browser or playlist editor causes thie crash after recent update (change from sometime in last year).  Switching between ncmpcpp/ncmpcpp-git in arch repos doesn't change it.   In fact I'm also getting it with a branch I made of the repo 3 years ago.  Hence I tried mpd and mpd-git both, which also didn't resolve it.  mpd was also updated at the same time, so likely something mpd is sending is causing an error to be thrown?

**Comment by djvs** [comment]
I also notice this, maybe related:

```
   what():  Malformed entity response line
                                              [1]    30539 abort (core dumped)  ncmpcpp
```

**Comment by sleepingPerson** [comment]
Similar issue came with last release *ncmpcpp-0.9 (2020-12-20)*

Starts fine with most startup screens like `ncmpcpp --screen=playlist`
But crushes with this startup screens: **browser** and **visualizer**
And also it breaks terminals formatting

```
Reading configuration from /home/bob/.config/ncmpcpp/config...
Playlist terminate called after throwing an instance of 'MPD::ClientError'
what():  No active MPD connection
zsh: abort (core dumped) ncmpcpp --screen=browser
```

**Comment by arybczak** [comment]
@sleepingPerson this is already fixed, see #432.

**Comment by arybczak** [comment]
@djvs you must've had something weird in your MPD database. If the problem persists, it's necessary to locate which database bit causes that and get rid of it.

**Comment by djvs** [comment]
Yes, some mp3s had malformed characters in their filenames or ID3 or something.
