### ISSUE TITLE
NCMPCPP sometimes can't fetch lyrics for songs with an apostrophe in the title

### ISSUE THREAD

**Issue by emilysnow2477** [ncmpcpp/ncmpcpp#364]
EDIT: It appears this isn't consistent. Some songs work. For instance, Sonata Arctica's "Don't Say a Word" seems to work just fine. I'm not sure what causes this discrepancy in behavior.

When using the built-in lyrics function for songs like Memphis May Fire - That's Just Life, Sleeping with Sirens - I'll Take You There, etc, it won't return lyrics properly, instead displaying a google search result. The resulting url doesn't contain an apostrophe (https://genius.com/Memphis-may-fire-thats-just-life-lyrics). 

Ideally, ncmpcpp would account for songs with an apostrophe in the title and display lyrics in the terminal as usual, as it's not an uncommon occurrence.

Pastebin: https://bin.privacytools.io/?fd3e3dc0d357db07#VTQlCqTaac1+G6YdeORl4oXCoDtsKb3oXgFwIfvPLVI=
OS: Arch
Terminal: St with zsh
Version: 0.8.2-10

**Comment by larson-carter** [comment]
@emilysnow2477 It appears that some of the sources are having issues with gathering the lyrics. Such as running out of sources. Can you try with a few online example albums and report back to me please?

**Comment by emilysnow2477** [comment]
@larson-carter Sure, what online example albums were you thinking of?

**Comment by 0x113** [comment]
Yeah, I have same problem with most song.

**Comment by ResponSySS** [comment]
It's clearly linked to the fetching and not to the filenames.

In a random playlist, the following WORKS:
Radiohead - [all songs] (OK Computer OKNOTOK 1997-2017)
LSD - Thunderclouds (Labrinth, Sia & Diplo Present... LSD)
Kanye West - Dark Fantasy (My Beautiful Dark Twisted Fantasy)
Kanye West - Power (My Beautiful Dark Twisted Fantasy)

The following does not:
Raekwon, Kanye West & Kid Cudi - Gorgeous  (My Beautiful Dark Twisted Fantasy)
Kanye West - Hell of a Life (My Beautiful Dark Twisted Fantasy)
[others from the same album]
SCH - Otto (JVLIVS)
Tyler, The Creator - I THINK (IGOR)


These are the songs as tagged by me in the format "{artist} - {title} ({album})".

**Comment by arybczak** [comment]
This was most likely related to broken fetchers in 0.8.2, closing.
