### ISSUE TITLE
[BUG] Two albums in a row with the same name but different artists are considered the same in playlist view

### ISSUE THREAD

**Issue by eramdam** [ncmpcpp/ncmpcpp#366]
**Describe the bug**
When a playlist has two albums with the same name but different artists in a row, it seems that ncmpcpp thinks they're the same album without looking at the artist/albumartist being different

**To Reproduce**
1. Add two albums with the same name from different artists in the playlist
2. Notice ncmpcpp thinking they're the same album

**Expected behavior**
Ncmpcpp should differentiate those two albums since they have different artist/albumartist tags.

**Screenshots/Logs**
I enabled `playlist_separate_albums` to make the problem obvious
![Screen Shot 2019-12-01 at 3 25 58 PM](https://user-images.githubusercontent.com/1409924/69922178-f1812a00-144e-11ea-865e-23c080494f85.png)

Obviously if the albums aren't in a row, the issue disappears 
![image](https://user-images.githubusercontent.com/1409924/69922197-11b0e900-144f-11ea-944c-f3718fc74242.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Terminal: iTerm2 3.3
 - Version ncmpcpp 0.8.2

**Additional context**

**Comment by arybczak** [comment]
Fixed in 89ebfbf73dbf68221de4e735ea75c4e7a4a7bf10.
