### ISSUE TITLE
How to enter non-ascii code in bindings?

### ISSUE THREAD

**Issue by FinlandAndy** [ncmpcpp/ncmpcpp#387]
Hi,

I'm trying to use a keyboard that sends a non-ascii code. I see from the bindings file that non-ascii are supported:-  

> Note: Function def_key accepts non-ascii characters.

What is the syntax for entering non-ascii? For example, if my keycode is 164 decimal, how do I use this with def_key?

##           action1

Cheers!

**Comment by arybczak** [comment]
What symbol does 164 corresponds to?

Let's say it's `ó`, then you can write `def_key "ó"` and it'll work.
