### ISSUE TITLE
[BUG]Does not recognize bluetooth headset to display sound

### ISSUE THREAD

**Issue by ingram1107** [ncmpcpp/ncmpcpp#391]
Ncmpcpp does work on my laptop with pulseaudio. However, it seems like it does not recognize my connected bluetooth headset to direct sound from the laptop audio to the headset. If I don't mute my laptop's audio, it will instantly choose my laptop audio over my connected bluetooth headset which is not desired by my need.

**Comment by arybczak** [comment]
This is a pulse audio related issue.
