### ISSUE TITLE
[BUG] ncmpcpp crashes when background lyrics fetching is active by default

### ISSUE THREAD

**Issue by BachoSeven** [ncmpcpp/ncmpcpp#394]
I started getting the following error followed by a quick crash when playing some songs, very frequently:
```
Unexpected error: basic_string::_M_construct null not valid
```

I stripped down my config until I identified that the crash was caused by the following option: `fetch_lyrics_for_current_song_in_background = yes`; I also found that this seems to happen on songs where lyrics cannot be found, and indeed even with the option turned off, trying to fetch lyrics (i.e. pressing ".") crashes with the same error on such songs.

The behavior is reproducible on my system with a config file consisting only of the above line, and then playing a song with lyrics which cannot be found.

**Desktop (please complete the following information):**
 - OS: ARCH
 - Terminal: zsh
 - Version 0.8.2

1st EDIT: a few corrections

2nd EDIT: Adding some info:
- when not using the option, manually trying to fetch lyrics freezes but doesn't crash the terminal
- I also realised that the issue is present only when it tries to fetch using Genius as a provider, meaning it breaks only when accessing genius.com
 Thus, this is maybe an issue with the API from genius, so I don't even know if it can really be fixed here.

3rd EDIT: it is not only genius, i got the same crashes with lyricwiki

**Comment by wimstefan** [comment]
I can confirm this issue and I'm very grateful that you've found the cause of these crashes! I was already re-compiling the whole system because I couldn't find the source of the problem :-)

- OS: Gentoo ~amd64
- Terminal: zsh 5.8 (x86_64-pc-linux-gnu)
- ncmpcpp version
``` 
ncmpcpp 0.9_dev
optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - clock
encoding detection: enabled
built with support for: ncurses taglib
```

**Comment by Yamagi** [comment]
I can confirm this for FreeBSD, too. After the last system upgrade some dependencies got updated and now ncmpcpp segfault when trying to fetch lyrics. Not all lyrics fetchers are broken but most.

**Comment by emilysnow2477** [comment]
It's a problem for OpenBSD folks as well.

https://marc.info/?l=openbsd-misc&m=159971108009387&w=2

**Comment by emilysnow2477** [comment]
Though I should revise that statement by mentioning that ncmpcpp crashes and dumps a core file for _all_ lyric fetching on OpenBSD as far as I can tell. It doesn't seem to be a situational thing like it is with others.

**Comment by emilysnow2477** [comment]
Though I should revise that statement by mentioning that ncmpcpp crashes and dumps a core file for _all_ lyric fetching on OpenBSD as far as I can tell. It doesn't seem to be a situational thing like it is with others.

**Comment by arybczak** [comment]
I never encountered that problem. Can you try with `master` branch and if this still happens, provide a meaningful backtrace?

**Comment by emilysnow2477** [comment]
@arybczak GDB backtrace of HEAD is in the mailing list thread I linked.

**Comment by arybczak** [comment]
ah, I see. The segfault is in the libc++ during destruction of std::mutex. What GCC version was ncmpcpp compiled with?

**Comment by emilysnow2477** [comment]
```
$ gcc -v
Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd6.8/4.2.1/specs
Target: amd64-unknown-openbsd6.8
Configured with: OpenBSD/amd64 system compiler
Thread model: posix
gcc version 4.2.1 20070719
```

**Comment by emilysnow2477** [comment]
Well, that's the version in base anyway. I built it using the ports system and the patch Stuart gave with this command:

`$ doas make repackage reinstall`

**Comment by arybczak** [comment]
That surely wasn't it, this version doesn't support C++14. I need to know the actual version is was built with.

**Comment by emilysnow2477** [comment]
Ah, my bad. That's the version of GCC in base, though typically packages are built with CLANG over in BSD land. 

```
$ clang++ -v
OpenBSD clang version 10.0.1
Target: amd64-unknown-openbsd6.8
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by arybczak** [comment]
Does that still happen? I can't reproduce.

**Comment by arobase-che** [comment]
I disabled the option.
I just re-enabled it and I can't reproduce.

It used to be a reproductible bug.

Thank you for your investigation.

**Comment by BachoSeven** [comment]
@arybczak I can confirm that this is not an issue anymore, running master. Closing this
