### ISSUE TITLE
[FEATURE] Add documentation for setting up the Genius lyrics fetcher

### ISSUE THREAD

**Issue by joaopaulobdac** [ncmpcpp/ncmpcpp#396]
I can't find a description on how the Genius lyrics fetcher should be set up.

I've been using the default fetchers but I frequently encounter errors in the lyrics. I find that lyrics from Genius tend to be correct more often than from other websites, so I wish to disable all the other fetchers and only use Genius.

**Comment by BachoSeven** [comment]
You can easily do this by changing the `lyrics_fetchers` array from the default configuration to a certain set of lyrics fetchers (i.e. [here](https://github.com/BachoSeven/dotfiles/blob/master/.config/ncmpcpp/config#L197)).

**Comment by joaopaulobdac** [comment]
I did that, but it never fetches any lyrics even though I can find them online. I'm guessing it needs an API key or login information to actually work.

**Comment by BachoSeven** [comment]
If that's the case I suggest you follow #394, as I've reported misbehaviour with Genius over there, and this might be related

**Comment by joaopaulobdac** [comment]
Were you experiencing crashes when using the genius fetcher before that issue? In my case, ncmpcpp doesn't crash but it never finds lyrics.

**Comment by BachoSeven** [comment]
no, I used to be able to fetch lyrics also with Genius, before the crashes. I would not be 100% certain but I think it did work

**Comment by yekoc** [comment]
@joaopaulobdac Which version of ncmpcpp are you using?
What you are describing reminds me of the behavior from before #374 
Thought I ought to mention this since the latest release tag in the repo is from 2018.

**Comment by joaopaulobdac** [comment]
I was on version 0.8.2.

> Thought I ought to mention this since the latest release tag in the repo is from 2018.

Oh wow I wasn't aware of that. I compiled ncmpcpp-git from the AUR and I can confirm I'm now able to fetch from Genius! Thank you so much. I'll close this issue since I didn't need to set up any configuration for it to work.
