### ISSUE TITLE
[FEATURE] Are there commands for ncmpcpp available which I can link to multimedia keys?

### ISSUE THREAD

**Issue by TheChymera** [ncmpcpp/ncmpcpp#402]
I would like to be able to pause, or switch to the next or previous songs even when not focusing on the window. Are there `ncmpcpp` commands available which I can bind to multimedia keys via my desktop manager?

**Comment by JacksonTaylorxyz** [comment]
You should be able to accomplish this via mpc/mpd commands. Depending on your setup there are a few different options out there to use, such as sxhkd, to bind them to keys/combinations. With sxhkd, you specify keys that run commands. I use a tiling window manager, so I don't have any sort of program that would overwrite these, if you're using a desktop environment they may already have a specific way to bind keys that could conflict with sxhkd.

**Comment by TheChymera** [comment]
ok, yes, I figured out how to do wthis via mpc, I was just thinking ncmpcpp might have analogous functionality built-in.
