### ISSUE TITLE
Can't Display Unicode Characters

### ISSUE THREAD

**Issue by ciarandeg** [ncmpcpp/ncmpcpp#403]
Hi, I've been trying to fix this unicode issue I'm running into and can't figure it out for the life of me. I know MPD is running in UTF-8, and I know my metadata is good, but ncmpcpp refuses to display foreign characters, even though my terminal is capable of doing so. Does anyone recognize this issue? Here's a screenshot of the issue, along with the config I'm using to troubleshoot and proof that the characters display properly in my terminal via mpc. I've tried adding `system_encoding = "utf8"` to my config, and all it does is add more garbled text into my album artist field.
https://i.imgur.com/52jt5WQ.png

**Comment by ciarandeg** [comment]
Fixed, it was a locale issue

**Comment by shibumi** [comment]
How was this fixed? I am running into the same problem :(
