### ISSUE TITLE
[BUG] Tag editor: cannot edit multiple titles

### ISSUE THREAD

**Issue by bratekarate** [ncmpcpp/ncmpcpp#410]
I am not sure if it is intentional or a bug, but I cannot edit multiple titles in the tag editor. Sometimes I have Songs in different formats and want to tag multiple tracks with the same title. On all other tags, I can hit enter in the mid menu and bulk change them. For title, this does not work.

Another use case is live sets, they have no name so I usually title them (or they are already titled) like `<ARTIST> @ <EVENT> <YEAR>`. So I bulk change the title of all in the folder to `@ <EVENT> <YEAR>` and insert the Artist individually. I know I could use a mass tagger tool, but this just happens once in a while for a couple files and this way feels like a simple solution.

If it's not a bug, I would suggest an error/warning, that titles cannot be bulk edited. Because otherwise it feels buggy and some time is wasted double checking the buttons pressed and making assumptions about the programs behaviour.

**Comment by arybczak** [comment]
It's an arbitrary restriction put there so that people don't set titles to the same value by accident as I thought it doesn't make much sense.

But since you have a use case, I lifted this restriction in 3b06b7e.
