### ISSUE TITLE
[FEATURE] more frequent releases

### ISSUE THREAD

**Issue by dvzrv** [ncmpcpp/ncmpcpp#412]
**Is your feature request related to a problem? Please describe.**
Fixes for e.g. lyrics plugins do not find their way to the user in stable versions.

Additionally, the last release is two years old.

**Describe the solution you'd like**
Tag a new release.

**Describe alternatives you've considered**
Build from master. As a distribution packager this is nothing that can be done though.

**Additional context**
n/a (aside from :sob: )

**Comment by XVilka** [comment]
Yes, latest release at the site marked more than 2 years ago: ncmpcpp-0.8.2 (2018-04-11)

**Comment by m040601** [comment]
First of all thanks to everyone actively involved in this project for all these years. I cant' imagine my life and others without this mpd client. I am sure there's also a "silent majority" of power mpd/ncmpcpp users that don't often come to github to check out how things are going.

> latest release at the site marked more than 2 years ago:

Indeed. 


Looking at the contributors page for the last 2 years, https://github.com/ncmpcpp/ncmpcpp/graphs/contributors?from=2018-08-28&to=2020-11-21&
type=c

One can see that there were very few commits, and most were merge requests
.
2 or 3 commits by,
larson-carter
spk
pvsr

1 commit by
wylfen
torstehu
sticken88

and others.


The project still gets many and issues and pull requests opened.
But many seem to simply remain  unanswered for a long time.
The home page was also last updated on 2018, https://rybczak.net/ncmpcpp/


But, https://github.com/arybczak seems to continue quite active on github, though.


Not wanting to sound ungrateful or to much demanding, would it be possible for arybczak to do a simple status update on the whole project ? 

-

**Comment by StoppingBuck** [comment]
Tagging @arybczak in case he doesn't get pinged for the above message

**Comment by arybczak** [comment]
Hey.

I apologize for almost abandoning the program - ironically I'm sometimes on the other side of this problem at work (i.e. when OSS library maintainer disappears) so I know that it can be frustrating.

Unfortunately there is only so much one person can do, especially in their free time and my free time is going to other things at the moment.

There was an attempt to pass maintainership to @larson-carter, but I somewhat dropped the ball on this by being too slow in some areas and he disappeared.

My current plan is to fix lyric fetchers, release 9.0 and we can go from there.

ncmpcpp used to have a bit more complicated release plan, i.e. new features used to go to `0.N` whereas bugfixes went to `0.(N-1).*`, but that's out of the window now really.

**Comment by larson-carter** [comment]
I'm still available to helping with the maintainership of this project. I just need clear communication and feedbacks.

**Comment by StoppingBuck** [comment]
@arybczak do you think you could pass maintainership to @larson-carter now? :slightly_smiling_face:

**Comment by arybczak** [comment]
I released 0.9.

Merry Christmas :christmas_tree:  :tada:

**Comment by thezeroalpha** [comment]
Thanks for your work @arybczak! I just created a PR to add the new version to Homebrew.
