### ISSUE TITLE
[BUG] Remove the LyricWiki lyric fetcher as the site has closed permanently

### ISSUE THREAD

**Issue by StoppingBuck** [ncmpcpp/ncmpcpp#413]
**Describe the bug**
LyricWiki was permanently shut down last month ([source](https://en.wikipedia.org/wiki/LyricWiki) ), and as such, we might as well remove the lyricwiki fetcher from the code as it is permanently broken.

**Comment by arybczak** [comment]
Fixed in https://github.com/ncmpcpp/ncmpcpp/commit/60b8071eea61b36d1b6409312931ebd71024c8e1.
