### ISSUE TITLE
[BUG]Can't fetch any lyrics

### ISSUE THREAD

**Issue by Unviray** [ncmpcpp/ncmpcpp#416]
**Describe the bug**
ncmpcpp can't fetch any lyrics. It just say `Not found` in every lyrics provider  
I check in genius website but the lyrics exists

**To Reproduce**
1. Play a song
2. Move cursor to the song
3. Click `l`

**Expected behavior**
It should show the lyrics

**Screenshots/Logs**
![Screenshot from 2020-10-17 10-40-40](https://user-images.githubusercontent.com/44167149/96331357-49c01b00-1065-11eb-877d-fdd3e063c0ae.png)

**Desktop (please complete the following information):**
 - OS: Arch 5.4.70-1-lts
 - Terminal: fish
 - Version: 0.8.2

**Comment by cubetastic33** [comment]
For me the lyrics fetchers didn't work when I installed it with pacman, but after seeing a reddit comment I installed the git version from the AUR, and now the lyrics fetchers work except for Lyricswiki. So I think this is fixed in the latest master.

**Comment by Unviray** [comment]
Thanks it works
