### ISSUE TITLE
[FEATURE / BUG] Media library view is slow to show albums and songs

### ISSUE THREAD

**Issue by hiqua** [ncmpcpp/ncmpcpp#418]
**Is your feature request related to a problem? Please describe.**
In media library view, there's a delay (at least 0.5ms on my machine) to show albums and songs when changing the artist (using up / down). This delay also prevents interactions  (meaning I cannot go to the right column before the albums are shown).

**Describe the solution you'd like**
Make the delay go away by speeding up the album and song retrieval procedure.

**Describe alternatives you've considered**
* Cache the neighboring entries so that the delay is not noticeable.
* At least make it possible to interact already (meaning, take into account that the user wanted to go to the right column, even if it was not shown yet).

**Additional context**
Just switched from ncmpc where I'm not used to delays, maybe there's something wrong with my config but I haven't changed anything yet.

**Comment by arybczak** [comment]
The delay is can be disabled in the config.

**Comment by hiqua** [comment]
Thanks, `data_fetching_delay` did the trick. Then the issue would be: shouldn't this be the default?
