### ISSUE TITLE
ncmpcpp: error while loading shared libraries: libboost_filesystem.so.1.72.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by BakedSnake** [ncmpcpp/ncmpcpp#426]
Started getting this error on launch after lattest ncmpcpp and boost update.

Not sure if it's a ncmpcpp problem or boost.

 - OS: Arch
 - Terminal: zsh

**Comment by arybczak** [comment]
It's an Arch issue, they need to rebuild the package (or you have to do it if you're using git version).

**Comment by BakedSnake** [comment]
Thanks, I guess I'll do it with the git version
