### ISSUE TITLE
[BUG] white(foreground) color is physically impossible to get displaying as foreground color.

### ISSUE THREAD

**Issue by exorcist365** [ncmpcpp/ncmpcpp#428]
**Describe the bug**
Will not display white color(foreground) as foreground color; instead displays gray (i tried my best)/

**Expected behavior**
Should display white

**Screenshots/Logs**
https://0x0.st/iFzF.jpg

**Desktop (please complete the following information):**
 - OS:arch linux
 - Terminal: st
 - Version 0.8.2

**Comment by arybczak** [comment]
are you sure this isn't just your terminal's "white"?

**Comment by exorcist365** [comment]
Yes.

**Comment by exorcist365** [comment]
The white/black(on a light theme) is showing just fine in the label where it says "Connected to localhost" as you can see in the screenshot.

**Comment by arybczak** [comment]
I don't see any white in the screenshot.

**Comment by exorcist365** [comment]
https://0x0.st/iFK_.jpg

**Comment by arybczak** [comment]
Have a look at the end of a help screen (F1), is there a white color there?

**Comment by exorcist365** [comment]
Ah. Well the help screen was not working for me when I tried to press it it did nothing but now it works and I solved it.
Thank you.

**Comment by arybczak** [comment]
Out of curiosity, what was the problem and the solution?

**Comment by exorcist365** [comment]
$(16_0) {%f} did what i wanted

**Comment by 6gk** [comment]
Hmm, since when can regular users assign / add labels?

**Comment by exorcist365** [comment]
¯\_(ツ)_/¯ but im not a member

**Comment by 6gk** [comment]
¯\\\_(ツ)\_/¯

you want to format like this when doing that face in markdown

![image](https://user-images.githubusercontent.com/40295114/102081699-5fcb3b80-3e5c-11eb-99c0-2d1938453286.png)
