### ISSUE TITLE
[BUG] Starting with startup_slave_screen or the --slave-screen causes a crash

### ISSUE THREAD

**Issue by silverbluep** [ncmpcpp/ncmpcpp#433]
**Describe the bug**
Whenever I try to launch with either `startup_slave_screen = <SCREEN>` config option defined, or the `--slave-screen <SCREEN>` argument passed; ncmpcpp quits with `[1] 99016 abort (core dumped)`.
If i manually use ctrl-l to set screen division and navigate screens; both screens work fine. But not by using the command line or the config option to have it as default behavior.

**To Reproduce**
1. Either set the config option `startup_slave_screen` or provide `--slave-screen` argument with a screen; such as `visualizer`
2. Run ncmpcpp

**Expected behavior**
ncmpcpp to not crash; and have two displays with the specified SCREENs.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Terminal: kitty 0.19.3
 - Shell: zsh 5.8
 - Version: ncmpcpp 0.9

**Additional context**
This crash happened when I updated from the previous version to version 0.9

**Comment by arybczak** [comment]
It's fixed in 0.9.1.
