### ISSUE TITLE
[BUG] ncmpcpp albumn art doesnt work with the recent update  (visualizer )

### ISSUE THREAD

**Issue by siduck76** [ncmpcpp/ncmpcpp#434]
I'm using this wrapper to get albumn art  https://github.com/alnj/ncmpcpp-ueberzug , but with the recent update the albumn art doesnt show at all and only visualizer shows :/ 
 
 
![image](https://user-images.githubusercontent.com/59060246/103299899-9e97ee80-4a23-11eb-8cd4-cce7f907b836.png)

its supposed to work like this 
![image](https://user-images.githubusercontent.com/59060246/103299983-d6069b00-4a23-11eb-8895-9281951e5464.png)

**Comment by arybczak** [comment]
This belongs to the `ncmpcpp-ueberzug` issue tracker.

**Comment by siduck76** [comment]
> This belongs to the `ncmpcpp-ueberzug` issue tracker.
my config works with older version of ncmpcpp tho , it just didnt work with 0.9.1 version .

**Comment by arybczak** [comment]
How are you using this? I suspect it's due to f3fe45f3ff6f12edcba501d074fa0e45bfada7ef - a fix for https://github.com/ncmpcpp/ncmpcpp/issues/353.

**Comment by siduck76** [comment]
I suppose ncmpcp's not printing anything on startup or song change , execute_on_song_change = printf test  doesnt show anything for me

**Comment by arybczak** [comment]
Yes, but the question is whether that's the issue. Does it work with 0.9?

**Comment by siduck76** [comment]
Im not sure , I didnt get any older versions of ncmpcpp. Im sure that the albumn art stopped working after I updated my system ( which updated ncmpcpp as well) .

**Comment by arybczak** [comment]
Can you check if dd0eac69 fixes the problem?

**Comment by arybczak** [comment]
Fixed by b902a2a.

**Comment by siduck76** [comment]
yeah :D 
 
![image](https://user-images.githubusercontent.com/59060246/103652076-8e829080-4f88-11eb-8c7a-c6c49ed4428c.png)

**Comment by siduck76** [comment]
@arybczak the albumn art  was working fine few days ago , and now it doesnt work again 
![image](https://user-images.githubusercontent.com/59060246/111991081-e79aa300-8b39-11eb-8bf9-8a0b7084b58f.png)
