### ISSUE TITLE
[BUG] execute_on_song_change can't execute printf/echo command (0.9.x)

### ISSUE THREAD

**Issue by owl4ce** [ncmpcpp/ncmpcpp#435]
**Hi, I just upgraded from version 0.8.2 to 0.9.1**
I have a problem with `execute_on_song_change` can't execute printf/echo, I use printf (pixbuf) to display album art inside ncmpcpp. But notify-send works.

<p align="center"><img src="https://user-images.githubusercontent.com/53987136/103470031-71d73480-4d9f-11eb-953c-aa4e733f4457.png"/></p>

<p align="center"><img src="https://user-images.githubusercontent.com/53987136/103470990-a6052200-4dac-11eb-84d8-3f52205c0fd7.png"/></p>

**Expected behavior (Screenshots 0.8.2)**

<p align="center"><img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/072e191f-a0a5-4be2-bc7a-55eb140b254f/deb5glz-9cbd5bec-efeb-4631-a87a-13380633cc48.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvMDcyZTE5MWYtYTBhNS00YmUyLWJjN2EtNTVlYjE0MGIyNTRmXC9kZWI1Z2x6LTljYmQ1YmVjLWVmZWItNDYzMS1hODdhLTEzMzgwNjMzY2M0OC5wbmcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.PScw6CPguJWLtacMxqLr_ZM2FhzqJyjt-4Z4c3LANIs"/></p>

**Desktop (please complete the following information):**
 - OS: Gentoo/Linux
 - Terminal: URxvt
 - Version 0.9.1
 
 Was it blocked on purpose?
[My configuration](https://github.com/owl4ce/dotfiles/tree/master/.ncmpcpp)

**Comment by arybczak** [comment]
> Was it blocked on purpose?

Yeah, in f3fe45f3ff6f12edcba501d074fa0e45bfada7ef because of https://github.com/ncmpcpp/ncmpcpp/issues/353.

I suppose that's also the cause of https://github.com/ncmpcpp/ncmpcpp/issues/434. Sigh.

I guess I should revert this change then :thinking:

**Comment by arybczak** [comment]
Can you check if dd0eac69 fixes the problem?

**Comment by owl4ce** [comment]
**Hi @arybczak** 
I have tried the git version, but it gave these results. Album art hasn't worked as it got these prints.
![2021-01-04-054150_919x482_scrot](https://user-images.githubusercontent.com/53987136/103490640-d225af00-4e4f-11eb-8255-2bcc6b32d7f5.png)

**Comment by arybczak** [comment]
Can you check now?

**Comment by owl4ce** [comment]
> Can you check now?

Yeah, now worked. Thank you for quick response.
![2021-01-04-063717_343x431_scrot](https://user-images.githubusercontent.com/53987136/103491553-60516380-4e57-11eb-85ac-aa14cb069c6d.png)
