### ISSUE TITLE
nohup.out on $HOME

### ISSUE THREAD

**Issue by DavidHenryThoreau** [ncmpcpp/ncmpcpp#443]
I'm using ncmpcpp 0.9.1, since the update (https://archlinux.org/packages/community/x86_64/ncmpcpp/), i'm getting an empty file nohup.out on $HOME.

shell : 

`ncmpcpp       
Reading configuration from /home/user/.ncmpcpp/config...`
 
`Connected to 127.0.0.1 nohup.out : la sortie est ajoutée à 'nohup.out'`

Each time i'm changing song i'm getting : `nohup.out : la sortie est ajoutée à 'nohup.out'`.
the file is still empty.

**Comment by arybczak** [comment]
I think this is fixed in master. Can you confirm?

wt., 12 sty 2021, 18:23 użytkownik DavidHenryThoreau <
notifications@github.com> napisał:

**Comment by DavidHenryThoreau** [comment]
It was the `execute_on_song_change` before i did not use backquotes and with new version they are needed.
