### ISSUE TITLE
Frequency Spectrum Visualizer

### ISSUE THREAD

**Issue by ghost** [ncmpcpp/ncmpcpp#445]
Is it possible to use the old frequency spectrum visualizer? Try as I might, I'm just not a fan of the new one. At all. Is there an option to use the old one that I'm just overlooking or has it been completely removed from the software? I'd rather not have to revert to an older version. Thanks for any assistance.

**Comment by arybczak** [comment]
> I'm just not a fan of the new one

What do you not like about it?

**Comment by KoO-303** [comment]
If you try to change the visualizer_look it still says the same as default the style won't change.
visualizer_look = ●▮ = default 
visualizer_look = "◆♫" = my style

https://i.postimg.cc/C1TJL1FP/new-version-visualizer.jpg 
https://i.postimg.cc/Wp7STTx8/visualizer-my.jpg

**Comment by robshizzle** [comment]
> 
> 
> If you try to change the visualizer_look it still says the same as default the style won't change.
> visualizer_look = ●▮ = default
> visualizer_look = "◆♫" = my style
> 
> https://i.postimg.cc/C1TJL1FP/new-version-visualizer.jpg
> https://i.postimg.cc/Wp7STTx8/visualizer-my.jpg

Exactly my issue with it as well. I see no reason why the old option was completely removed just because a newer "better" option was patched in.

**Comment by KoO-303** [comment]
Well not much good having an option you can't use. Maybe their going to remove visualizer_look an just say with the default option.
If so I will be saying with 0.8.2 everything works just fine and album art works with ueberzug.
https://ibb.co/vhYwgzn

**Comment by arybczak** [comment]
> If you try to change the visualizer_look it still says the same as default the style won't change.

You need to disable `visualizer_smooth_look` and it'll work. It's described in the docs.

> album art works with ueberzug.

This is #434 and fixed in master.

**Comment by KoO-303** [comment]
Opps my mistake. 
visualizer_spectrum_smooth_look = no

Nice tip too.
If you want more "jumpiness" of the visualizer (as in 0.8.2), set visualizer_spectrum_dft_size to 1.

Thanks for your help..
