### ISSUE TITLE
[BUG] Crash when cancelling out of the password prompt

### ISSUE THREAD

**Issue by deviant** [ncmpcpp/ncmpcpp#446]
Cancelling out of the password prompt using <kbd>Ctrl-C</kbd> or <kbd>Ctrl-G</kbd> causes ncmpcpp to crash with the following error:

```
terminate called after throwing an instance of 'NC::PromptAborted'
  what():  
```

This is because the exception in question is only caught in the [first section of the main loop](https://github.com/ncmpcpp/ncmpcpp/blob/master/src/ncmpcpp.cpp#L233-L236), and not when [handling `MPD::ServerError`](https://github.com/ncmpcpp/ncmpcpp/blob/master/src/ncmpcpp.cpp#L245-L248), which is where the [password is read](https://github.com/ncmpcpp/ncmpcpp/blob/master/src/status.cpp#L197).

**Comment by arybczak** [comment]
Fixed in 541b8d7aabb61af662b8f6e9acccf12e963b7f89.
