### ISSUE TITLE
[BUG] Crash when idling in the password prompt for one minute

### ISSUE THREAD

**Issue by deviant** [ncmpcpp/ncmpcpp#447]
If the password prompt is left open for exactly sixty seconds, ncmpcpp will crash with the following error:

```
terminate called after throwing an instance of 'MPD::ClientError'
  what():  Broken pipe
```

Judging by its strace output, this happens when a `status` message is sent to mpd. I don't think any other messages are sent by ncmpcpp in the period between the prompt being shown and the crash, so I think it's safe to assume that a timeout is being hit somewhere.

**Comment by arybczak** [comment]
Fixed in 541b8d7aabb61af662b8f6e9acccf12e963b7f89.
