### ISSUE TITLE
[BUG] visualizer_look setting not applied to spectrum mode

### ISSUE THREAD

**Issue by chebro** [ncmpcpp/ncmpcpp#450]
**Describe the bug**
There seems to be a problem with the `visualizer_look` setting, while it correctly displays the character in ellipse/wave modes, it doesn't apply the same in the frequency spectrum mode. I've tried tried setting several different characters but the setting isn't applied to the spectrum mode.

**Expected behavior**
Apply the specified character defined in `visualizer_look`.

**Screenshots/Logs**

![2021-02-01-213722_1920x1080_scrot](https://user-images.githubusercontent.com/54331348/106486263-77778580-64d7-11eb-9837-47487a50d764.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Kitty (zsh)
 - Version: ncmpcpp 0.9.2

**Comment by arybczak** [comment]
See #445.
