### ISSUE TITLE
[FEATURE] Partial database updates.

### ISSUE THREAD

**Issue by enthus1ast** [ncmpcpp/ncmpcpp#458]
On bigger databases, and slower machines (eg. raspberry pi) the current update mechanism
could easily take multiple minutes.

It would be nice if ncmpcpp could command the mdp server to just update a particular folder.

For example if a folder in the remote browser is highlighted.
And an (eg.) 'UpdateDatabaseFolder' command is generated via keyboard (eg key 'f').
Ncmpcpp could issue a command like:

```
update path/to/highlighted/folder
```

to just update the given folder.

Or/and when a file inside a folder is highlighted then the current dir could be updated.

Reasoning: 
I often find myself adding just one song to an "unsorted" folder, then i issue an database update via ncmcpp (key 'u')
which could easily take ~10 minutes.
In constrast, doing it by hand via ncat or mpc is usually done in seconds.

**Comment by j-n-f** [comment]
That seems to be how it was written:

https://github.com/ncmpcpp/ncmpcpp/blob/f47cf7f37c2bae64fc66da32c197b40ab424f4ca/src/actions.cpp#L1221-L1231

Have you looked at the logs for `mpd` to see what it's doing? It seems to be sparse by default, but you might try increasing `log_level` (see `man mpd.conf`) to see if `ncmpcpp` is passing the wrong path, or if `mpd` is unable to interpret it.

I would note from `man mpc`:

```man
       update [--wait] [<path>] - Scans for updated files in the
              music directory.  The optional parameter <path> (relative to the music directory) may limit the scope of the update.

              With --wait, mpc waits until MPD has finished the update.
```

**Comment by enthus1ast** [comment]
> Have you looked at the logs for mpd to see what it's doing?

Not yet, but i should have and i will. Thank you for the answer

**Comment by enthus1ast** [comment]
Ok i tried again from inside the folder, works as expected, could be that this is a newer version of ncmpcpp or that i've made a mistake before. [Closed]
