### ISSUE TITLE
Add Hex Code instead of basic color names.

### ISSUE THREAD

**Issue by KoO-303** [ncmpcpp/ncmpcpp#479]
Instead of the below standard colors names as below would it be possible to add Hex Code options. #000000 #FFFFFF

song_columns_list_format = "(25)[#CCCCCC]{a} (24)[white]{b} (35)[yellow]{t} (5)[magenta]{l}"

black
red
green
yellow
blue
magenta
cyan
white

**Comment by flipflop133** [comment]
Should be added, it's a must!
