### ISSUE TITLE
Broken lyrics fetcher for genius.com

### ISSUE THREAD

**Issue by ian-s-mcb** [ncmpcpp/ncmpcpp#487]
**Describe the bug**
The lyrics fetcher for genius.com doesn't display any lyrics (or error message) for any song I've tried. 

**To Reproduce**
1. Set lyrics fetcher to genius.com
2. Play any mainstream song (eg. Coldplay - "The Scientist")
3. Press show lyrics command

At this point, ncmpcpp will display an blank screen and no error message. I noticed a lyrics .txt file is created by ncmpcpp for the the song but the file is empty. For comparison, the fetcher for azlyrics.com works fine for the same songs that didn't work for genius.com.

**Expected behavior**
Lyrics, or at the very least an error messge, are shown.

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.12.9
 - Terminal: Bash 5.1.8, Alacritty 0.8.0
 - ncmpcpp version: 0.9.2 (installed via pacman)

**Comment by arybczak** [comment]
Can you try master? It should work there.

**Comment by ian-s-mcb** [comment]
@arybczak Works like a charm. Thank you!

I really dig ncmpcpp. You've done a great job with it.

**Comment by dvzrv** [comment]
@arybczak a new release would be much appreciated :tada: The latest version is from early 2021, so it does not have any fixes you might have applied and users of ncmpcpp in downstream distributions will still suffer from this issue.
