### ISSUE TITLE
[BUG] can't find lyrics, even if the song is on the sources

### ISSUE THREAD

**Issue by LonelyMusicDisc** [ncmpcpp/ncmpcpp#492]
**Describe the bug**
can't find/fetch lyrics, even if the song is on the sources (ex: genius)

**To Reproduce**
1. Go to 'playlist', 'browse' or you're preferred method of playing songs through ncmpcpp
2. Press 'l' or whatever key the find lyrics is bound  to.

**Expected behavior**
one of the sources will get fetched and show you the lyrics.

**What happens**
every single one says "Not found", even though the song is popular and is on at least 3 of those sites.

**Screenshots/Logs**
I don't know how it would help, but here, I'd like to know if there's a way to get a log for lyrics
https://i.imgur.com/ZBooSOQ.png

**Desktop (please complete the following information):**
 - OS: Mint XFCE
 - Terminal: i3-sensible-terminal
 - Version 20.2 (I'm guessing it means os version)

**Comment by arybczak** [comment]
What ncmpcpp version are you using? If it's not 0.9.2, you need to upgrade.

**Comment by LonelyMusicDisc** [comment]
> What ncmpcpp version are you using? If it's not 0.9.2, you need to upgrade.

8.2, do I need to build it from source? because apt isn't saying anything about an update/upgrade.

**Comment by arybczak** [comment]
I have no idea how Mint packaging works, so I can't help you here. You might need to compile from source.

**Comment by LonelyMusicDisc** [comment]
okay I'll compile from source, I'll probably make a new issue because my compiled version is a bit funky.
