### ISSUE TITLE
[BUG] Bitrate not displayed for Vorbis or Opus files

### ISSUE THREAD

**Issue by tsweet64** [ncmpcpp/ncmpcpp#493]
**Describe the bug**
When playing a Vorbis or Opus file with bitrate display enabled, the audio bitrate is not displayed in ncmpcpp like it is for mp3 and flac files.

**To Reproduce**
1. Enable or toggle bitrate display
2. Add a Vorbis or Opus audio file to the playlist and play it.

**Expected behavior**
The audio's bitrate is displayed.

**Screenshots/Logs**
![screenshot](https://user-images.githubusercontent.com/41387413/127070401-c4dea424-986f-4f4a-9405-765e7b24ee6a.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Konsole
 - Version ncmpcpp/0.9.2 and mpd/0.22.9

**Additional context**
Let me know if this is a bug/limitation in mpd itself and I'll report it there instead.

**Comment by arybczak** [comment]
> Let me know if this is a bug/limitation in mpd itself and I'll report it there instead.

I'm pretty sure that's it, because ncmpcpp simply takes the bitrate from the result of the `status` command sent to mpd.

**Comment by tsweet64** [comment]
Okay, makes sense. I opened an issue at MusicPlayerDaemon/MPD#1213

Should I close the issue here or leave it until it gets confirmed by upstream?

**Comment by tsweet64** [comment]
I'll close this since it is definitely due to mpd itself. As described in the other issue, there is a workaround for now by disabling the vorbis and opus decoders in mpd. This forces it to fallback to ffmpeg, which should provide the bitrates.
