### ISSUE TITLE
[BUG] invalid value: lyricsmania

### ISSUE THREAD

**Issue by LonelyMusicDisc** [ncmpcpp/ncmpcpp#494]
**Describe the bug**
when I try to run ncmpcpp, I get an error saying it can't fetch lyricsmania

**To Reproduce**
1. compile ncmpcpp
2. make an install
3. try to run it

**Expected behavior**
ncmpcpp runs.

**what actually happens**
_n o ._

**Screenshots/Logs**
```
Reading configuration from /home/lonely/.config/ncmpcpp/config...
WARNING: Variable 'visualizer_fifo_path' is deprecated and will be removed in 0.10 (replaced by visualizer_data_source).
WARNING: Variable 'visualizer_sync_interval' is deprecated and will be removed in 0.10 (set 'buffer_time' parameter of your MPD audio output to '100000' (100ms) or lower if you experience synchronization issues between audio and visualization).
Error while processing option "lyrics_fetchers": invalid value: lyricsmania
```

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Terminal: i3-sensible-terminal
 - Version 20.2 Uma
 - ncmpcpp 9.2

**Comment by arybczak** [comment]
You have lyricsmania in your config file but it's no longer supported, remove it.
