### ISSUE TITLE
[FEATURE] Bind to a name without a socket inode

### ISSUE THREAD

**Issue by cinerea0** [ncmpcpp/ncmpcpp#499]
**Is your feature request related to a problem? Please describe.**
In the [mpd documentation](https://mpd.readthedocs.io/en/stable/user.html#listeners), a possible option for binding the daemon to an address is to bind to a name without a socket inode on the filesystem, with the example given being `bind_to_address "@mpd"`. It is a bit frustrating that ncmpcpp cannot connect to a socket of this type.

**Describe the solution you'd like**
I would like it so that ncmpcpp can connect to sockets of this type, maybe by allowing the `mpd_host` option to be set to a value such as `@mpd`.

**Describe alternatives you've considered**
If this is too technically challenging to implement, I think simply documenting that this connection option is unavailable would be fine.

**Comment by arybczak** [comment]
Fixed in 40e4f98e.
