### ISSUE TITLE
[BUG] Unable to add multiple genres to `flac` files

### ISSUE THREAD

**Issue by aflyingpumpkin** [ncmpcpp/ncmpcpp#511]
**Describe the bug**
When using the built in tag editor I am unable to add in multiple genres to `flac` files.

**To Reproduce**
1. Use the `Tiny tag editor` on a `flac` file.
2. Add in multiple genres using the delimiter set in the config file.
3. Save
4. Open the same file back up in the `Tiny tag editor` and noe that only one tag is shown.

**Expected behavior**
All tags should be shown, like what occurs in mp3 files.

**Desktop (please complete the following information):**
 - OS: I use arch btw
 - Terminal: st
 - Version 0.9.2

**Comment by Sacha-Ringenbach** [comment]
+1 ! it doesn't work for Artists either,

For example
`ArtistA | ArtistB`
Gets saved as :
`ArtistB`

Here is the content of ~/.config/ncmpcpp/config
`mpd_music_dir = /mnt/500gb/Music/`

Everything works as expected with an mp3 file

**Comment by balejk** [comment]
I believe this has already been solved by #463.

**Comment by aflyingpumpkin** [comment]
After switching to the version on git instead of the latest release this was fixed!
