### ISSUE TITLE
Unknown Option visualizer_fifo_path

### ISSUE THREAD

**Issue by Decapitater** [ncmpcpp/ncmpcpp#516]
Unable to start ncmpcpp 
fifo file is entact 
mpd works 
mpd folder -  $HOME/.mpd 
ncmpcpp - $HOME/.ncmpcpp

(ncmpcpp)config=

[config.txt](https://github.com/ncmpcpp/ncmpcpp/files/7537881/config.txt)

mpd.conf=

[mpd.txt](https://github.com/ncmpcpp/ncmpcpp/files/7537880/mpd.txt)

@larson-carter 
@vejkse

**Comment by WMCB-Tech** [comment]
`ncmpcpp` version 0.10.x would completely remove that and was deprecated since 0.9.x, can you tell what version of ncmpcpp you're using?

**Comment by Decapitater** [comment]
@WMCB-Tech  0.10_dev , arch linux

**Comment by WMCB-Tech** [comment]
that version replaced `visualizer_fifo_path` to `visualizer_data_source` so change it in your config,

**Comment by Decapitater** [comment]
Worked !
> that version replaced `visualizer_fifo_path` to `visualizer_data_source` so change it in your config, 

@WMCB-Tech  unknown option visualizer_sync_interval

**Comment by Decapitater** [comment]
@WMCB-Tech  any help ?

**Comment by WMCB-Tech** [comment]
> `WARNING: Variable 'visualizer_sync_interval' is deprecated and will be removed in 0.10 (set 'buffer_time' parameter of your MPD audio output to '100000' (100ms) or lower if you experience synchronization issues between audio and visualization).`

@Decapitater You may specify `buffer_time` in mpd config and remove `visualizer_sync_interval` in your ncmpcpp config

**Comment by Decapitater** [comment]
worked 
@WMCB-Tech 
Unknown option: progressbar_boldness

**Comment by Decapitater** [comment]
i uploaded my configs it would be really great if you could check this

**Comment by Decapitater** [comment]
@WMCB-Tech any help ?

**Comment by WMCB-Tech** [comment]
for `progressbar_boldness`, not sure coz i don't use it. i'll look into it later

**Comment by Decapitater** [comment]
Umm alright @WMCB-Tech

**Comment by Decapitater** [comment]
@WMCB-Tech  ?? Any help pls

**Comment by WMCB-Tech** [comment]
@Decapitater 
In the [changelog](https://rybczak.net/ncmpcpp/) in `ncmpcpp` v8:
> Format information can now be attached to selected color variables in the configuration file. Because of that variable ‘progressbar_boldness’ is now deprecated in favor of extended ‘progressbar_color’ and ‘progressbar_elapsed_color’

I think you should fiddle around `progressbar_color` and `progressbar_elapsed_color’` instead

**Comment by Decapitater** [comment]
@WMCB-Tech can i see your config if you won't mind ?

**Comment by GabenCrying** [comment]
I still get this issue even after replacing visualizer_fifo_path to visualizer_data_source

**Comment by Decapitater** [comment]
I left it 2 months ago lol @GabenCrying  I would suggest a new installation with a good guide

**Comment by Toni500github** [comment]
i'm maybe late but i resolved it by changing to the branch 0.8x
