### ISSUE TITLE
[BUG] Changing to "playlist editor" make the whole window freeze

### ISSUE THREAD

**Issue by Kritiqual** [ncmpcpp/ncmpcpp#521]
**Describe the bug**
As the title says :||

**To Reproduce**
1. Go to 'playlist editor'
2. The whole window freeze, cannot press anything, nothing more is shown
3. Have to reopen another terminal and ncmpcpp

**Expected behavior**
Showing something?

**Desktop (please complete the following information):**
 - OS: Arch 
 - Terminal: kitty
 - Version 0.9.2 (from AUR)

**Comment by Inky1003** [comment]
also happens with the official Manjaro repositories
