### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dnaik42** [ncmpcpp/ncmpcpp#523]
**Describe the bug**
`visualizer_look` only doesn't work on spectrum, but works on all other visualizer styles

**To Reproduce**
```
visualizer_fifo_path = /tmp/mpd.fifo
visualizer_sync_interval = 25
visualizer_output_name = "my_fifo"
visualizer_in_stereo = yes
visualizer_type = "spectrum"
visualizer_look = ┃┃
```

**Expected behavior**
The spectrum visualizer uses the ┃ character instead of the default block character █. This does not happen. All other visualizer styles use ┃ but not spectrum.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Terminal: kitty
 - Version: 0.9.2

**Comment by arybczak** [comment]
This is configurable via the `visualizer_spectrum_smooth_look`.
