### ISSUE TITLE
[BUG] Int overflow re: seeking to position in song via status bar

### ISSUE THREAD

**Issue by djvs** [ncmpcpp/ncmpcpp#532]
**Describe the bug**
Int overflow in song % bar in status bar.   Clicking on status bar in excess of 256 characters from the left seeks to n % 256 characters from the left.  

**To Reproduce**
1. Make ncmpcpp window wider than 256 characters.
2. Click right of the 256th character
3. Song does not seek to that location.

**Expected behavior**
Song seeks to the expected location.

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Linux 5.16.12
 - Terminal: zsh
 - Version 0.10_dev.  I think I compiled from git back when I did my PR the other week.

**Comment by djvs** [comment]
https://stackoverflow.com/questions/16778275/ncurses-bug-mouse-coordinates-to-beyond-222-width-or-height-terminal

**Comment by djvs** [comment]
Oh yeah, this isn't even an ncmpcpp bug.  Tmux (or more likely, just my lack of fine tuned tmux config) just isn't supporting SGR 1006 - same terminal with ncmpcpp works fine without tmux.

**Comment by arybczak** [comment]
ncmpcpp supports extended mouse tracking, just the urxvt version. Works fine for me in xterm and konsole (also used to work in urxvt, but I'm not using it anymore).

See https://github.com/ncmpcpp/ncmpcpp/blob/417d7172e5587f4302f92ea6377268dca7f726ad/src/curses/window.cpp#L374.

**Comment by djvs** [comment]
Well, it doesn't work in urxvt with tmux either.  I'm just running ncmpcpp without tmux for now, but something's definitely off.

**Comment by djvs** [comment]
FWIW it seemed from reading like this was an area where urxvt had broken with what everyone else had standardized.

**Comment by djvs** [comment]
Hi @arybczak  - I took this to tmux and they tossed it back over here: https://github.com/tmux/tmux/issues/3834

**Comment by djvs** [comment]
"ncmpcpp is not turning on either of the extended mouse modes supported by tmux (SGR or UTF-8), so the maximum position will be 222. You will need to ask the ncmpcpp developers to add support for SGR mouse mode (UTF-8 is definitely not recommended anymore)."
