### ISSUE TITLE
Media Key support in the ncmpcpp.

### ISSUE THREAD

**Issue by pakosaan** [ncmpcpp/ncmpcpp#535]
Is there any way to map the media keys for ncmpcpp control as other desktop won't let me to reassign as it conflicts with others.
Or, Are there any alternative to ncmpcpp.

**Comment by DestroyerAce** [comment]
@pakosaan you can use mpDris2 which let you control mpd with media keys 
https://github.com/eonpatapon/mpDris2

**Comment by Randoragon** [comment]
You can also achieve this without ncmpcpp - by using any kind of keybind daemon (xbindkeys, sxhkd, ...) to send commands to MPD with the `mpc` utility. Here's a simple config for sxhkd, for instance:
```
XF86AudioPlay
	mpc toggle
XF86AudioStop
	mpc stop
XF86AudioNext
	mpc next
XF86AudioPrev
	mpc prev
```
