### ISSUE TITLE
[BUG] Fetching lyrics from azlyrics returns almost always empty text

### ISSUE THREAD

**Issue by Eolien55** [ncmpcpp/ncmpcpp#543]
**Describe the bug**
When trying to fetch lyrics from azlyrics, the returned text is more often that not an empty text.

**To Reproduce**
1. Try fetching lyrics for a song (eg, Welcome To The Machine, Pink Floyd)
2. Get empty text

**Expected behavior**
Not getting empty text.

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Artix
 - Terminal: st and zsh
 - Version 0.9.22

**Additional context**
The problem is with azlyrics, who changed their API. Now, just fetching the HTML is not enough as it forces JavaScript rendering
to get the actual lyrics. The easiest to solve this problem would probably to use the new API, or to use a different provider. I've also had several problems with the genius.com, returning this text : 

![](https://user-images.githubusercontent.com/78177054/171509263-d06f5b22-6b50-4ab0-ab00-00f487dcc31d.png)

**Comment by exorcist365** [comment]
I have the same issue, it was working a few days/weeks ago though.

**Comment by Eolien55** [comment]
The problem is caused by the way `ncmpcpp` fetches lyrics. While it previously provided lyrics in plain-text format, it now forces the use of a (probably locked-down) API

**Comment by Eolien55** [comment]
So it appears azlyrics.com just changed a bit their HTML, which is causing the error. #544 fixes this issue.

**Comment by arybczak** [comment]
Azlyrics fetcher was removed.
