### ISSUE TITLE
[BUG] metrolyrics.com has changed into metrolyrics.pro 

### ISSUE THREAD

**Issue by charlie39** [ncmpcpp/ncmpcpp#546]
**Describe the bug**
metrolyrics.com has changed to metrolyrics.pro ( the wiki article says it went
down in 2021 )
and that's why perhaps ```ncmpcpp --test-lyrics-fetchers``` always returns
failed for me.

**To Reproduce**

1. run ```ncmpcpp --test-lyrics-fetchers```

**Expected behavior**
should return ok.

**Comment by arybczak** [comment]
Metrolyrics fetcher is gone.
