### ISSUE TITLE
[BUG] Separators are between artist/title pair instead of per albums

### ISSUE THREAD

**Issue by arbitrary-dev** [ncmpcpp/ncmpcpp#556]
**Describe the bug**
When pressing `!` I see sepearators between all songs in an album with various artists.
Though selecting all songs in an album with `B`, as well as jumping between albums with `]` & `[` works correctly.

**Expected behavior**
`!` toggles separators per album_artist/album_title[/disk] tags instead.

**Desktop:**
 - OS: Gentoo
 - Terminal: Alacritty
 - Version `ncmpcpp-0.9.2`

**Comment by arybczak** [comment]
This was fixed by https://github.com/ncmpcpp/ncmpcpp/pull/472.
