### ISSUE TITLE
[BUG] Genius.com lyrics fetcher shows incomplete lyrics

### ISSUE THREAD

**Issue by DestroyerAce** [ncmpcpp/ncmpcpp#566]
**Describe the bug**
Using genius.com to fetch lyrics always skips some paragraphs 

**To Reproduce**
1. Choose any song 
2. Use genius.com to fetch lyrics

**Expected behavior**
Show complete lyrics

**Screenshots/Logs**
![Bistro by MF DOOM lyrics fetched by genius.com fetcher](https://i.imgur.com/VcSQkor.png)

**Desktop:**
 - OS: Fedora 37
 - Terminal: Kitty (with fish shell)
 - Version ncmpcpp 10_dev

**Comment by saltasatelites** [comment]
Same problem here. In my case genius.com always shows the same long text of its website:

 `"How to Format Lyrics:
Type out all lyrics, even repeating song parts like the chorusLyrics should be broken down into individual linesUse section headers above different song parts like [Verse], [Chorus], etc.Use italics (<i>lyric</i>) and bold (<b>lyric</b>) to distinguish between different vocalists in the same song partIf you don’t understand a lyric, use [?]
To learn more, check out our transcription guide or visit our transcribers forum." `

So the next fetchers doesn't wok as they understand that the lyrics have been found. 
(sorry for my grammar, isn't my first language)

**Comment by o0nd7ots** [comment]
I sometimes get the same message
https://github.com/ncmpcpp/ncmpcpp/issues/570

**Comment by arybczak** [comment]
It works in master.
