### ISSUE TITLE
[FEATURE] "--cmd" feature like vim/neovim

### ISSUE THREAD

**Issue by glyh** [ncmpcpp/ncmpcpp#579]
**Is your feature request related to a problem? Please describe.**

I frequently realize I would most run some command and quit ncmpcpp immediately. 

**Describe the solution you'd like**
Support an aditional argument `--keys`, which simulates the key strokes on startup.

**Describe alternatives you've considered**
support `--cmd` like  arguments like vim.

**Comment by PingalPie** [comment]
if you want to use it in one line the use `mpc` that works well
