### ISSUE TITLE
[BUG] 'azlyrics.com' endpoint doesn't return lyrics

### ISSUE THREAD

**Issue by Ocramoi** [ncmpcpp/ncmpcpp#585]
**Describe the bug**
While using azlyrics, the default fetcher, lyrics are not display, even though there is no error message.

**To Reproduce**
1. Using Manjaro, enter `ncmpcpp` and try accessing lyrics for the current song using `azlyrics.com` as the fetcher.
2. Wait for data to be fetched

**Expected behavior**
The lyrics should be displayed if present in the website, if not an error message should be displayed.

**Screenshots/Logs**
![image](https://github.com/ncmpcpp/ncmpcpp/assets/9422402/ccfdb2dd-db03-4e52-a6fb-f512eec8c8b9)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Terminal: zsh
 - Version: up to date with branch `main` at commit [9f44edf](https://github.com/ncmpcpp/ncmpcpp/commit/9f44edf0b1d74da7cefbd498341d59bc52f6043f)

**Comment by bpampel** [comment]
This is a known bug (see e.g. https://github.com/ncmpcpp/ncmpcpp/issues/543 or https://github.com/ncmpcpp/ncmpcpp/issues/570). Fixed by https://github.com/ncmpcpp/ncmpcpp/pull/544 but sadly not merged

**Comment by marurunk** [comment]
How long this doesn't work? I don't understand.

https://github.com/ncmpcpp/ncmpcpp/assets/100788648/1fc5c862-dacb-4842-bfcc-7f42b00d4100

**Comment by bpampel** [comment]
@marurunk There has not been a release in the last years and none is planned, so this will continue to fail.

However, there are fixes available for the lyrics issues (see the links I posted above) but you would have to apply them and compile the code yourself. If you can't do that, you're sadly out of luck until a more stable dev team arises.

**Comment by arybczak** [comment]
Removed the azlyrics fetcher.
