### ISSUE TITLE
[Question] 6th mode / empty mode in alternative user interface

### ISSUE THREAD

**Issue by NecRaul** [ncmpcpp/ncmpcpp#588]
![image](https://github.com/ncmpcpp/ncmpcpp/assets/40130066/7f40c75e-9884-45e9-9cf8-40fc7de3da96)
I understand that these modes are repeat, random, single, consume and crossfade in the image order, but then what is the 6th mode?

In the classic user interface modes get added as you activate them but that's not the case for the alternative user interface and it clearly shows 6 modes.

**Comment by o0nd7ots** [comment]
Its an indicator for when you're running a database update.

ps. next time I suggest using `[rzscx-]` instead of attaching a screenshot, or attaching a bigger one as right now this does neither well
