### ISSUE TITLE
request a new release for including taglib 2.0 support

### ISSUE THREAD

**Issue by chenrui333** [ncmpcpp/ncmpcpp#595]
👋 I saw some recent changes have included taglib 2.0 support, any timeline cutting a new release for them? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/166984

**Comment by chenrui333** [comment]
cc @arybczak

**Comment by quite** [comment]
Still I don't think it is complete, the PKGBUILD in Arch Linux's AUR (like user pkgs) still applies this little patch for building towards taglib2 https://aur.archlinux.org/cgit/aur.git/tree/020-ncmpcpp-taglib2-fix.patch?h=ncmpcpp-git

**Comment by arybczak** [comment]
See #576.
