### ISSUE TITLE
[BUG] core dump with narrow terminal

### ISSUE THREAD

**Issue by ropery** [ncmpcpp/ncmpcpp#596]
Trying to run ncmpcpp in a narrow terminal produces core dump:

    $ echo $COLUMNS
    50
    $ ncmpcpp
    terminate called after throwing an instance of 'std::logic_error'
    what():  constructed window doesn't fit into the termnal
    [1]    86591 IOT instruction (core dumped)  ncmpcpp

Be warned: This leaves the terminal in a dirty state, so test in a new terminal window so you can just close it.
Tested against the latest git master.

**Comment by arybczak** [comment]
Fixed by 37aea91be14a4a941464c933d7a20d7e29aaee41.
