### ISSUE TITLE
[BUG] is libcurl really an optional dependency?

### ISSUE THREAD

**Issue by fkobi** [ncmpcpp/ncmpcpp#603]
According to the readme, curl is an optional dependency.
I wanted to reflect that with a Gentoo ebuild.
However ["The binary links against libcurl, so it is needed both at build time & run time."](https://github.com/gentoo/gentoo/pull/37782#discussion_r1695267498).

To confirm this on the latest commit build I have deleted libcurl.so. That got me `ncmpcpp: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory`.

Doesn't that mean that curl is not an optional dependency?

**Comment by NexAdn** [comment]
Looking at configure.ac also indicates that it is pulled in unconditionally:

https://github.com/ncmpcpp/ncmpcpp/blob/68daf44032784a5b5b74781a9bf3826053eff4a2/configure.ac#L244-L256

**Comment by arybczak** [comment]
It's not, I fixed the readme.
