### ISSUE TITLE
[FEATURE] playback speed 

### ISSUE THREAD

**Issue by pjhfggij** [ncmpcpp/ncmpcpp#606]
**Is your feature request related to a problem? Please describe.**
I would like to speed up playback of some songs.

**Describe the solution you'd like**
Introduce new keybinding to control speed (e.g. [ and ] as in mpv)

**Describe alternatives you've considered**
mpv

**Comment by arybczak** [comment]
Does MPD allow this? If it doesn't, it's feature request for MPD.

**Comment by pjhfggij** [comment]
sorry, I forgot that this interfaces to mpd. No, there is no such control in mpd
