### ISSUE TITLE
[README] Update it to explicitly state the project is feature complete and in maintenance mode

### ISSUE THREAD

**Issue by m040601** [ncmpcpp/ncmpcpp#607]
First of all, thanks to @arybczak for taking the time to release 0.10.

I personally very much liked these ones.

```
• Column widths are now configurable via media_library_column_width_ratio_two,
  media_library_column_width_ratio_three and playlist_editor_column_width_ratio.
• Seeking now accepts the hh:mm:ss format.
• Column view can now display full filepaths.
```

Now lets keep in mind that this tool is a much loved, widespread, daily
used and a core treasure for many, many generations of people.

One should then not be astonished to know that simply having people understand and accept that:

- the project is alive and cared for
- its main maintainer is still around

Is important and much appreciated.

It might not satisfy everyone's wishes and the huge backlog of feature
requests. But it makes everything crystal clear. And it makes people stop
guessing. And maybe also stop opening and duplicating even more new unreasonable requests.

Now, you already did all that, https://github.com/ncmpcpp/ncmpcpp/issues/576#issuecomment-2248692746

```
arybczak (Collaborator) • Jul 24, 2024 • Edited
1 ❤️ 

  FWIW the project is not abandoned, it's in maintenance mode. I still use it more or less
  daily (interchangeably with the TIDAL client), but it's feature complete for me and I
  don't have much time to review/request changes on open PRs.

  If there is a hard breakage (like it was with taglib 2.0), it will be fixed, but I
  wouldn't expect any new big features 🙂

View the full review: https://github.com/ncmpcpp/ncmpcpp/issues/576#issuecomment-2248692746
```

Now my simple request.

Why dont you just write down exactly that ? In the right place. In the README.

Simply change this, 

```
# NCurses Music Player Client (Plus Plus)

## ncmpcpp – featureful ncurses based MPD client inspired by ncmpc

### Main features:
* tag editor
......
```

To this,

```
# NCurses Music Player Client (Plus Plus)

## ncmpcpp – featureful ncurses based MPD client inspired by ncmpc

### Status

The project is considered feature complete and is in maintenance mode.
If there is a hard breakage, it will be fixed.

There are no new big features to be expected.

There is very limited time dedicated to:

- review or respond to new feature requests
- review or respond to pull requests

### Main features:
* tag editor
......
```

It only costs you a few key presses and characters.

It would simplify, reduce and stop the
amount of useless comments and speculations on the issues queue. 

It would help the whole project with a more beautiful, cleaner, smaller, trimmed down issue list.

It would make it easier for you to look eventually look at what is being reported, and see/respond to what is really
important/prioritaire/urgent and might really need a bugfix.

Thanks in advance.

PS: The "Discussions" github forum like functionality.

Perhaps opening the "Discussions" feature on github would be a more appropriate venue/forum ?
To give people the space to talk, without overburding the project with new issues ?

**Comment by arybczak** [comment]
Thanks for the kind words and a suggestion, I updated the README and opened up discussions.
