### ISSUE TITLE
[BUG] the word 'red' appears at the top of each column

### ISSUE THREAD

**Issue by riquezjp** [ncmpcpp/ncmpcpp#614]
**Describe the bug**
in column view 4 & 6, the word 'red' appears like a tag surrounding the top lines of album & song  name.
Example : 
redTresspassred  |  redBlack Sheep - On the wallred

**Screenshots/Logs**
![Screenshot_2024-10-03-15-32-32_1920x1080](https://github.com/user-attachments/assets/8158dd53-36cc-40f8-90d4-638879a4df9a)

**Desktop (please complete the following information):**
 - OS: Archcraft 2024.07
 - xfce4 terminal:  zsh 5.9
 - Version ncmpcpp 0.10

**Additional context**
Ive noticed this problem for a few years, but yesterday i did a clean install of my OS & put ncmpcp on there. Right away this 'red' tag was there.

**Comment by miblodelcarpio** [comment]
I'm not sure about the album column, but I can get the string "red" into the song column by putting it in the `song_library_format` setting, e.g.

    song_library_format = "{%n. }red{%t}|{%f}$R{$3%l$9}"

Changing `red` to `$2` there instead styles the string red. Maybe your config contains instances of `red` that need changing to `$2`?

**Comment by riquezjp** [comment]
This is what the end of my `~/.ncmpcpp/config` file looks like.

You'll notice the `song_library_format` seems ok, but there is a suspicious `red` (without quotes)
in the `current_item_inactive_column_prefix ` .
I tried making that "red" but there was no effect. **Do I need to run a cmd to cache the config file?**

This is a totally fresh installed system & ncmpcpp, no edits up till this point have been made.
Although I am now wondering if this is a bug related to the distro since i do see the distro owners name in the file.

```
### Song list ###
song_status_format		 = "$7%t"
song_list_format 		 = "  %t $R%a %l  "
song_library_format 	 = {{%a - %t} (%b)}|{%f}
song_columns_list_format = "(53)[white]{tr} (45)[blue]{a}"

### Colors ###
main_window_color 					= "blue"
current_item_prefix 				= "$(blue)$r"
current_item_suffix 				= "$/r$(end)"
current_item_inactive_column_prefix = red
current_item_inactive_column_suffix = red
color1 = "white"
color2 = "red"
```

**Comment by miblodelcarpio** [comment]
Ah yeah, I've just been launching ncmpcpp afresh to pick up the config changes.

I have these two settings:

    current_item_inactive_column_prefix = $(246)$b$r
    current_item_inactive_column_suffix = $/r$/b$(end)

And the defaults for these, which Arch preserves in `/usr/share/doc/ncmpcpp/config`, are:

    current_item_inactive_column_prefix = $(white)$r
    current_item_inactive_column_suffix = $/r$(end)

Yeah, having Archcraft's owner's name in the file does sound suspiciously like they've tried to customise it. Could be worth just getting [the default](https://github.com/ncmpcpp/ncmpcpp/blob/master/doc/config). It'll also probably describe what `$(white)$r` and `$/r$(end)` mean because, honestly, they're pretty cryptic to me.

**Comment by arybczak** [comment]
```
current_item_inactive_column_prefix = red
current_item_inactive_column_suffix = red
```

You're getting `red` as a prefix and suffix because that's exactly what you requested :thinking: You need to use the format for colors if you want a red text or background or whatever.

```
current_item_inactive_column_prefix = "$(yellow_238)"
current_item_inactive_column_suffix = "$9"
```

Here's an example.
