### ISSUE TITLE
Tag Editor: contextualize database update after save

### ISSUE THREAD

**Issue by litemotiv** [ncmpcpp/ncmpcpp#615]
When doing a regular database update from a subdirectory, only the current directory will be processed, which results in quick update. When editing tags a full database update follows which takes significantly longer. 

**To Reproduce**

Regular / expected behaviour:

- Go to a an album subdirectory and press `u`
- Contextual database update starts and finishes quickly

When tag editing:

- Edit one or more tags in an album directory and press `save`
- Full database update starts and takes long to finish

The desired behaviour is that saving tags also initiates a local / contextual update only for the current (sub)directory.

Tested on 0.9.2.

**Comment by arybczak** [comment]
This should work as expected on 0.10, please reopen if this is not the case.

**Comment by litemotiv** [comment]
> This should work as expected on 0.10, please reopen if this is not the case.

I'm currently on 0.10.1 and it appears that it is not working as intended yet. Editing tags and saving still results in a full database update. 

Please let me know if you need any other information.
