### ISSUE TITLE
[BUG] Segmentation fault when reversing an empty playlist

### ISSUE THREAD

**Issue by jwren0** [ncmpcpp/ncmpcpp#616]
**Describe the bug**
Reversing an empty playlist causes a segmentation fault.

**To Reproduce**
- If the playlist isn't empty, open ncmpcpp to clear it, then close ncmpcpp
- Reopen ncmpcpp
- Try to reverse the empty playlist
- A segmentation fault occurs

**Expected behavior**
The program doesn't segfault.

**Screenshots/Logs**
![image](https://github.com/user-attachments/assets/9e6fa184-e8b7-43cc-9b85-948126fd5d1d)

**Desktop (please complete the following information):**
 - OS: Void Linux (x86_64-musl)
 - Terminal: Alacritty
 - Version: 0.9.2

**Comment by arybczak** [comment]
Please try with 0.10 and reopen if this still happens, I can't reproduce with 0.10.

**Comment by jwren0** [comment]
I downloaded the source from the 0.10 tag and compiled locally, as it's not available on the void repos yet.
I still experienced a segfault.

**Comment by arybczak** [comment]
What command are you using for this? Ctrl+r?

**Comment by jwren0** [comment]
yes, ctrl+r

**Comment by arybczak** [comment]
Ah ok, starting ncmpcpp with empty playlist is crucial. Alright, thanks.
